### PR TITLE
[fix]: emitter events consts export

### LINKED ISSUE #32: Emitter events constants export
Hi! Thank you for your lib first, great work

I've wanted to use emitter events, like mentioned in README, but realized that `EmitterEvents` constants not exported from index file. And haven't another module in `dist` folder that I can use. Should it be exported from main file, or I missed something ? 

- I've built reproduce with error https://github.com/upteran/test-swr-imports
- version of package: 3.1.2

Tested locally own fix with export, sent PR with it. Added export and types for constants, the simplest fix I think, if you have another solution, I can update it.

### PR DESCRIPTION
**Pull request by upteran**
### Description
- add emitter events constants export from index file
- ~add emitter events types for using it in code~

### Related Issue
Closes #32

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -11,6 +11,8 @@ export const EmitterEvents = {
   revalidateFailed: 'revalidateFailed',
 } as const
 
+export type EmitterEvents = (typeof EmitterEvents)[keyof typeof EmitterEvents]
```
Comment (jperasmus) [inline src/constants.ts:14]: This adds a bit of ambiguity since the type clashes with the name of the constants map and the type is not strictly necessary to fix the problem.

Do you mind dropping the type declaration here and just keeping the `EmitterEvents` map export you have in the `index.ts` file? That should be enough to fix the problem.

If you want the type available as well, you can instead rename it to the singular form (`EmitterEvent`) and export that alongside the `EmitterEvents` map.

**Review by jperasmus — CHANGES_REQUESTED** [review]

File: src/constants.ts (hunk 1 above)
Comment (jperasmus) [reply src/constants.ts]: Thanks!

**Review by jperasmus — APPROVED** [review]
